export const SET_BUN = "SET_BUN";
export const SET_INGREDIENT = "SET_INGREDIENT";
export const REMOVE_INGREDIENT = "REMOVE_INGREDIENT";
export const REORDER_INGREDIENTS = "REORDER_INGREDIENTS";
export const SET_TOTAL_PRICE = "SET_TOTAL_PRICE";
